modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "project_me"
version = "${version}"
displayName = "Project Me"
authors = "Zbx1425, Burning_TNT"
description = '''
Create player projection entities for players on other sharded servers.
'''
#logoFile = ""

[[dependencies.project_me]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.project_me]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "project_me.mixins.json"
